Add endpoints to request nonce and message to sign
safe-global/safe-auth-service pull request #10
Opened 2024-07-31 17:13 UTC by falvaradorodriguez

Closes #3

2024-08-01 10:16 UTC, Uxio0 requested changes

2024-08-01 10:16 UTC, Uxio0 commented on app/main.py
> +    description="API to grant JWT tokens for use across the Safe Core{API} infrastructure.",
```suggestion
    description="API to grant JWT tokens for using across the Safe Core{API} infrastructure.",
```

2024-08-01 10:16 UTC, Uxio0 commented on app/siwe/message_service.py
> +DEFAULT_STATEMENT = (
Maybe this should be configurable via settings

2024-08-01 10:16 UTC, Uxio0 commented on app/siwe/nonce_repository.py
> +    redis_client = Redis.from_url(settings.REDIS_URL, decode_responses=True)
I think there should be a common place to get a Redis instance, so in my opinion there should be a Redis Repository or something like that.  If Redis is required in more places we will have multiple connections to Redis opened in different places.

The contents of this nonce repository has some business logic in it, so maybe it should be a service, but not strong opinion here.

2024-08-01 10:16 UTC, Uxio0 commented on app/tests/test_router_about.py
> +import unittest
I think this should be belong to a a folder `tests/routers/test_about.py`

Also I feel that `/tests` package should be outside of `/app/`, maybe in `/tests/`, so `/test/` discovery is faster, also that way we would be able to leave tests out of the packaged app. But I see that `FastAPI` recommends doing it your way, so it looks good to me

2024-08-01 10:16 UTC, Uxio0 commented on app/tests/test_siwe_message_service.py
> +import unittest
Same, file should be inside of `/tests/services/`

2024-08-01 10:16 UTC, Uxio0 commented on docker-compose.yml
> +      - --appendonly yes
Well done, I understand we need Redis persistency

2024-08-01 10:16 UTC, Uxio0 commented on docker/web/Dockerfile
> +ENV ENV_FILE=.env.docker
AFAIK this environment variable is only set when building the Dockerfile, is that what you want?

2024-08-01 10:16 UTC, Uxio0 commented on requirements/prod.txt
> +hiredis==3.0.0
You don't need to add hiredis as you are already adding it with `redis[hiredis]`

2024-08-01 10:34 UTC, falvaradorodriguez commented on docker/web/Dockerfile
> +ENV ENV_FILE=.env.docker
Yes, that's what I'm looking for. In that case, it will assign the correct REDIS URL (for example) when using the Dockerfile. We are doing the same in other services with Django. Correct me if I'm wrong

2024-08-01 13:23 UTC, falvaradorodriguez commented on docker/web/Dockerfile
> +ENV ENV_FILE=.env.docker
Yes, you are right. It was a mistake.

2024-08-01 13:23 UTC, falvaradorodriguez commented on app/tests/test_siwe_message_service.py
> +import unittest
Done [here](https://github.com/safe-global/safe-auth-service/pull/10/commits/2b3a73c7603e5ae9705919ac0066dbf0beb6184b)

2024-08-01 13:24 UTC, falvaradorodriguez commented on app/tests/test_router_about.py
> +import unittest
Done [here](https://github.com/safe-global/safe-auth-service/pull/10/commits/2b3a73c7603e5ae9705919ac0066dbf0beb6184b)

2024-08-01 13:24 UTC, falvaradorodriguez commented on app/siwe/message_service.py
> +DEFAULT_STATEMENT = (
Done [here](https://github.com/safe-global/safe-auth-service/pull/10/commits/2b3a73c7603e5ae9705919ac0066dbf0beb6184b)

2024-08-01 13:29 UTC, falvaradorodriguez commented on app/siwe/nonce_repository.py
> +    redis_client = Redis.from_url(settings.REDIS_URL, decode_responses=True)
Yes, and it is also more clear.I thought it would be the only point of use, but it doesn't have to be. In the near future we can use redis for any other feature 👌

2024-08-01 13:30 UTC, falvaradorodriguez commented on app/siwe/nonce_repository.py
> +    redis_client = Redis.from_url(settings.REDIS_URL, decode_responses=True)
Done [here](https://github.com/safe-global/safe-auth-service/pull/10/commits/2b3a73c7603e5ae9705919ac0066dbf0beb6184b)

2024-08-02 10:27 UTC, Uxio0 approved these changes

2024-08-02 10:40 UTC, merged